In [127]:
import pandas as pd

In [128]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [129]:
s.dtype

dtype('int64')

In [130]:
s.values

array([10, 20, 30, 40, 50])

In [131]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [132]:
print(s.name)

None

In [133]:
s.name = "calories"

In [134]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [135]:
# Indexing:
s[0]

np.int64(10)

In [136]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [137]:
s[:3]

0    10
1    20
2    30
Name: calories, dtype: int64

In [138]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [139]:
# iloc --> Location based Indexing
s.iloc[3]

np.int64(40)

In [140]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [141]:
index=["apple","banana","grapes","orange","strawberry"]

In [142]:
s.index= index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [143]:
s['grapes']

np.int64(30)

In [144]:
s['orange']

np.int64(40)

In [145]:
#loc --> label based indexing
s.loc['grapes']

np.int64(30)

In [146]:
# In label based indexing your start as well as stop value both are included in the output.
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [147]:
fruit_protein ={
    "Avacado":2.0,
    "Guava":2.6,
    "Blackberries":2.0,
    "Oranges":0.9,
    "Banana":1.1,
    "Apples":0.3,
    "Kiwi":1.1,
    "Pomegranate":1.7,
    "Mango":0.8,
    "Cherries":1.0
}

In [148]:
s2=pd.Series(fruit_protein,name="Protein")
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [149]:
# Conditional Selection:
s2[s2>1]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [150]:
# Logical operators : and,or,Not
[(s2>0.5) & (s2<=2)]

[Avacado          True
 Guava           False
 Blackberries     True
 Oranges          True
 Banana           True
 Apples          False
 Kiwi             True
 Pomegranate      True
 Mango            True
 Cherries         True
 Name: Protein, dtype: bool]

In [151]:
# Not operation
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [152]:
# Modifying the series:
s2["Mango"]=2.8

In [153]:
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [154]:
import numpy as np
ser=pd.Series(['a',np.nan,1,np.nan,2])
ser.notnull().sum()

np.int64(3)

In [155]:
#DataFrame:
data ={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000,60000,70000,62000,np.nan,50000]
}

In [156]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [157]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [158]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [159]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [160]:
# loc and iloc
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [161]:
df.loc[1:4,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR

In [162]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [163]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [164]:
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [165]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [166]:
df.shape

(6, 4)

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [168]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [169]:
# Broadcasting:
df["Salary"]=df["Salary"]+5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [170]:
#Renaming Columns:
df.rename(columns={"Department":"Dept"},inplace=True)

In [171]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [172]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [173]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [174]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [175]:
df["Promoted Salary"]=df["Salary"]*10

In [176]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [177]:
# Data Cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [178]:
df.dropna(how="any") #any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [179]:
df.dropna(how="all") # if all the values in any row are null then we drop

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [180]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [181]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [182]:
df["Age"].fillna(df["Age"].fillna(method="ffill"))

/tmp/ipykernel_832/335091665.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(df["Age"].fillna(method="ffill"))

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [183]:
df["Name"]=df["Name"].replace("Charlie","Rose")

In [184]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [185]:
#Duplicates:

df_dup=df[df.duplicated()]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [186]:
df_dup=df[df.duplicated(keep="first")]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  55000.0         550000.0

In [187]:
df=df.drop_duplicates()

In [188]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [189]:
# Invalid Values
#Lambda ---> Python
df["Promoted Salary"]=df["Promoted Salary"].apply(lambda x: x/10 if x> 650000 else x)

/tmp/ipykernel_832/1212643446.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"]=df["Promoted Salary"].apply(lambda x: x/10 if x> 650000 else x)

In [190]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [192]:
name="alice_fernandes"
df[["first_name","last_name"]]=df["name"].str.split("_")

KeyError: 'name'

In [193]:
# apply and lambda
def multiplying_age(x):
  return x*2

df["Age"]=df["Age"].apply(multiplying_age)

/tmp/ipykernel_832/3753187931.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].apply(multiplying_age)

In [194]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  55000.0         550000.0
1    Bob  60.0       IT  65000.0         650000.0
2   Rose  70.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [195]:
df["Age"]=df["Age"].apply(lambda x: x/2)

/tmp/ipykernel_832/71323140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].apply(lambda x: x/2)

In [196]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [197]:
# Joins and Merges:
department_info ={
    "Department":["HR","IT","Finance"],
    "Location":["New York","San Francisco","Chicago"],
    "Manager":["Laura","Steve","Nina"]
}

In [198]:
df2=pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [199]:
pd.concat([df,df2])

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,25.0,HR,55000.0,550000.0,NaN,NaN,NaN
1,Bob,30.0,IT,65000.0,650000.0,NaN,NaN,NaN
2,Rose,35.0,Finance,75000.0,75000.0,NaN,NaN,NaN
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [203]:
pd.concat([df,df2],axis=1)

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Alice,25.0,HR,55000.0,550000.0,HR,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,IT,San Francisco,Steve
2,Rose,35.0,Finance,75000.0,75000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN